### ISSUE TITLE
Notepad Window Title Change

### ISSUE THREAD

**Issue by deathchurch** [yaakov-h/Notepad.Extensions.Logging#3]
When you first run notepad the window title is as expected "Untitled - Notepad" and if you do not mouse over the window or make it active the logger will continue to work. If you do mouse over the notepad window or indeed make notepad active the window title changes to "*Untitled - Notepad" and the logger will stop working as you are looking for the window named with out the *.

Before 
![image](https://user-images.githubusercontent.com/37252590/82533215-c1336200-9b3a-11ea-8d9a-038e5a230c77.png)

After
![image](https://user-images.githubusercontent.com/37252590/82533240-c8f30680-9b3a-11ea-9569-34489b849fad.png)

**Comment by yaakov-h** [comment]
Yeah, I noticed this one as well.
