### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by DamionGans** [yaakov-h/Notepad.Extensions.Logging#4]
Right now the logger assumes the user has an English Windows machine (mine is not).
My suggestion is instead to find an open window from the notepad.exe program and open that.

**Comment by yaakov-h** [comment]
Finding the window based on process name is fairly trivial, but it'll be a lot trickier to identify a window with an open or saved document versus a transient, unsaved one.

**Comment by 4lexKislitsyn** [comment]
Hi. If providing a window name is suitable way to fix this problem, I can create an PR soon. Wait for feedback.
