### ISSUE TITLE
Provide window finder and write functions as nuget package

### ISSUE THREAD

**Issue by 4lexKislitsyn** [yaakov-h/Notepad.Extensions.Logging#7]
Now we can write to notepad but cannot configure the format of messages. There are a lot of libraries that has own renderers (Serilog, NLog, etc.). Is there way to move searching and writing functions in separate nuget package? It will allow extend logging libraries.

**Comment by yaakov-h** [comment]
It's simple enough to copy and paste. I believe someone else has already written a Serilog plugin too.

**Comment by 4lexKislitsyn** [comment]
yeap, I just think that copy/paste is not good way 😄
